name: Build Classes JSON

on:
  push:
    branches:
      - main            # <-- change to 'master' if your default branch is master
    paths:
      - "classes.xlsx"
      - "generate_classes.py"
      - ".github/workflows/build.yml"
  workflow_dispatch:    # allow manual run from the Actions tab

permissions:
  contents: write       # <-- REQUIRED so the action can push commits

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Verify required files exist
        run: |
          echo "Repo root contents:"
          ls -la
          test -f classes.xlsx || (echo "::error::classes.xlsx is missing at repo root" && exit 1)
          test -f generate_classes.py || (echo "::error::generate_classes.py is missing at repo root" && exit 1)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -V
          pip -V
          pip install --upgrade pip
          pip install pandas openpyxl
          python - << 'PY'
          import pandas, openpyxl
          print("pandas:", pandas.__version__)
          print("openpyxl:", openpyxl.__version__)
          PY

      - name: Generate JSON
        run: python generate_classes.py

      - name: Show changes (for debugging)
        run: |
          git status
          git diff -- classes.json || true

      - name: Configure Git and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "wetrusteditor-gif"
          git config user.email "wetrusteditor@gmail.com"
          git add classes.json
          git commit -m "Auto-update classes.json from Excel [skip ci]" || exit 0
          git push origin HEAD:${{ github.ref_name }}
